### ISSUE TITLE
Consider making Catalog.mapGeneric and Catalog.mapSpecific private

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#29]
Catalog.mapGeneric and Catalog.mapSpecific were made public to pass as parameters to RuleChecker constructor. Consider offering some other abstraction to RuleChecker.

**Comment by KatieProchilo** [comment]
`mapGeneric` and `mapSpecific` are now private. Created an accessor for `mapGeneric` since RuleChecker requires it. Did not create an accessor for `mapSpecific` since it's never accessed outside of catalog.ts. 

Closed with https://github.com/MikeHopcroft/PrixFixe/commit/92b4c8fce7bc8c8ba250df1c094b41941cc51354.
