### ISSUE TITLE
RuleChecker.isValidChild() throws in the absence of partial key matches

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#36]
In the following code, `reduce()` throws when `predicates` is empty, which can happen when there are no partial key matches for `par`.
~~~
    isValidChild = (par: KEY, child: KEY): boolean => {
        const predicates = this.tensorWalker(
            par,
            this.childTensor
        ) as ValidChildPredicate[];

        // Evaulate each predicate and take the logical-or
        const result = predicates
            .map(predicate => predicate(child))
            .reduce((x, y): boolean => x || y);

        return result;
    };
~~~

I suspect the fix is 
~~~
        const result = predicates
            .map(predicate => predicate(child))
            .reduce((x, y): boolean => x || y, false);
~~~

We should investigate whether this is, in fact the right fix, and determine if a similar problem exists elsewhere in the codebase.

**Comment by SpaceKatt** [comment]
Good catch. Currently, the only place where `reduce` could be used on an empty array is here where you fixed it. `grep` shows that this is the only case of the `reduce` function being used.

I suspect that more instances may pop up when the functionality of `RuleChecker` is expanded, due to the way that we are aggregating functions by using partial keys. I'll remember to specify a default value next time and close this issue for now.
